.catalog:
    name: "resilio"
    version: "v2.5.12"
    description: "resilio sync"
    questions:
     - variable: "DATA_FOLDER"
       description: "Data folder"
       label: "data folder"
       required: true
       type: "string"
       default: "/path/to/folder"
     - variable: "TRAEFIK_PORT"
       description: "Traefik port"
       label: "Traefik port"
       required: true
       type: "int"
       default: 8888
     - variable: "TRAEFIK_URL"
       description: "Rules for traefik url : 'Host:stack.yourdomain.com'"
       label: "Host:stack.yourdomain.com"
       required: true
       type: "string"
     - variable: "TRAEFIK_AUTH"
       description: "Basic auth in csv format : User:Hash,User:Hash. Default test/test123"
       label: "Basic auth"
       required: true
       type: "string"
       default: "test:$apr1$m5NOypU8$TfPxBTXOeOfnGSX4Mbe9t1"