name: BOT IRC
description: |
  # Description of the Catalog Entry
version: v0.1
category: application
maintainer: MikaXII<mika@recalbox.com>
license: # The license
projectURL: # A URL related to the catalog entry
