name: BOT IRC
description: |
  # Description of the Catalog Entry
version: v0.1
category: application
maintainer: MikaXII<mika@recalbox.com>
license: Creative C
projectURL: https://github.com/MikaXII/sopel-docker
