ghost:
  image: recalbox/ghost
  environment:
  - GHOST_URL="${ghost_url}"
  - DB_HOST="${db_host}"
  - DB_USER="${db_user}"
  - DB_PASSWD="${db_passwd}"
  - DB_NAME="${db_name}"
  - IP_LISTEN="${ip_listen}"
  - PORT_LISTEN="{port}"
  ports: 
  - ${port}:2368/tcp
  labels:
  - traefik.domain: geekael.fr
  - traefik.port: '2368'
  - traefik.enable: stack




