ghost:
  image: ghost:1.16.2-alpine
  restart: always
  volumes:
    - ${ghost_data}:/var/lib/ghost/content
  ports:
    - ${public_port}:2368
  environment:
    - NODE_ENV=production
    - url=${url}
