version: '2'

services:

  nextcloud:
    image: nextcloud:13-apache
    volumes_from:
      - nextcloud-data
    ports:
      - ${NEXTCLOUD_PORT}:80
    depends_on:
      - mariadb
    labels:
      io.rancher.sidekicks: nextcloud-data
      io.rancher.container.hostname_override: container_name
      io.rancher.scheduler.affinity: traefik.enable=true, traefik.domain=${traefik_domain}, traefik.port=80, traefik.frontend.rule=${traefik_frontend_url}, traefik.frontend.auth.basic=${traefik_basic_auth}

  nextcloud-data:
    image: nextcloud:13-apache
    entrypoint:
      - /bin/true
    volumes:
      - /var/www/html
    labels:
      io.rancher.container.start_once: 'true'
      io.rancher.container.hostname_override: container_name

  mariadb:
    image: mariadb:10
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASS}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASS}
    labels:
      io.rancher.sidekicks: mariadb-data
      io.rancher.container.hostname_override: container_name

  mariadb-data:
    image: mariadb:10
    entrypoint:
      - /bin/true
    volumes:
      - /var/lib/mysql
    tty: true
    labels:
      io.rancher.container.start_once: 'true'
      io.rancher.container.hostname_override: container_name

